version: '3.8'

services:
  backend-agendas:
    build: .
    container_name: backend-agendas-api
    ports:
      - "3001:3001"
    environment:
      # ===== CONFIGURACIÓN BÁSICA =====
      NODE_ENV: production
      PORT: 3001
      API_VERSION: "1.0.0"
      APP_NAME: "API de Agendas Médicas"
      
      # ===== CORS =====
      ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:3001,http://10.129.180.151"
      
      # ===== BASE DE DATOS ORACLE =====
      DB_USER: hvq_gsoria
      DB_PASSWORD: "P4nDeCochol4te"
      DB_CONNECT_STRING: "172.16.241.62:1521/SML"
      DB_POOL_MIN: 2
      DB_POOL_MAX: 10
      DB_POOL_INCREMENT: 1
      DB_POOL_TIMEOUT: 300
      
      # ===== SERVICIOS EXTERNOS =====
      EXTERNAL_AUTH_URL: "http://10.129.180.161:36560/api3/v1/Auth/login"
      EXTERNAL_AUTH_USERNAME: "middleware_dev"
      EXTERNAL_AUTH_PASSWORD: "DevMH@2025!"
      EXTERNAL_AUTH_REFRESH_URL: ""
      EXTERNAL_API_BASE_URL: "http://10.129.180.161:36560/api3/v1"
      EXTERNAL_MEDICOS_ENDPOINT: "/medico"
      
      # ===== ESQUEMAS DE BASE DE DATOS =====
      EDITOR_CUSTOM_SCHEMA: "EDITOR_CUSTOM"
      AGND_AGENDA_SEQUENCE: "SEQ_AGND_AGENDA"
      
      # ===== LOGS =====
      LOG_LEVEL: info
      LOG_FILE_PATH: /var/log/agendas-api.log
      
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/var/log
    networks:
      - agendas-network

networks:
  agendas-network:
    driver: bridge
